# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0002_auto_20170512_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.ManyToManyField(to='dialogue.Country'),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='movie',
            name='plot',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='imdb_id',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
