# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0003_auto_20170513_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='link',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.CharField(max_length=10),
        ),
    ]
