# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0004_auto_20170514_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='country',
            field=models.ManyToManyField(to='dialogue.Country'),
        ),
        migrations.AddField(
            model_name='series',
            name='plot',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='series',
            name='runtime',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='series',
            name='year',
            field=models.CharField(max_length=20),
        ),
    ]
